### ISSUE TITLE
Error 500 after upgrade to 3.11.0

### ISSUE THREAD

**Issue by Laul0** [matomo-org/matomo#14698]
## Summary

I upgraded the Matomo version from 3.10.0 to 3.11.0 yesterday.
Since I upgrade my server (on docker), I can track my visitor anymore.

## Current behavior

On my website, from the dev console, I have the following error message:

```
https://myserver.com/matomo.php?ping=1&idsite=[Site ID]&rec=1&r=645547&h=10&m=29&s=26&url=https%3A%2F%2Fmysite.com%2F&_id=1f281c9653116d4a&_idts=1557243117&_idvc=73&_idn=0&_refts=1564063882&_viewts=1564063882&_ref=https%3A%2F%2Ft.co%2FtuTVpuUy1b&send_image=1&pdf=1&qt=0&realp=0&wma=0&dir=0&fla=0&java=1&gears=0&ag=0&cookie=1&res=1920x1200&gt_ms=889&pv_id=RO2QL2
[Error] Failed to load resource: the server responded with a status of 500 () (matomo.php, line 0)
```

From my server log, I have this message:

```
[Thu Jul 25 14:31:03.970646 2019] [php7:error] [pid 56] [client [IP]:57066] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Piwik\\Tracker\\GoalManager::detectGoalsMatchingUrl(), 2 passed in /bitnami/matomo/plugins/Goals/Tracker/GoalsRequestProcessor.php on line 92 and exactly 4 expected in /opt/bitnami/matomo/core/Tracker/GoalManager.php:131\nStack trace:\n#0 /bitnami/matomo/plugins/Goals/Tracker/GoalsRequestProcessor.php(92): Piwik\\Tracker\\GoalManager->detectGoalsMatchingUrl(1, Object(Piwik\\Tracker\\ActionPageview))\n#1 /opt/bitnami/matomo/core/Tracker/Visit.php(152): Piwik\\Plugins\\Goals\\Tracker\\GoalsRequestProcessor->afterRequestProcessed(Object(Piwik\\Tracker\\Visit\\VisitProperties), Object(Piwik\\Tracker\\Request))\n#2 /opt/bitnami/matomo/core/Tracker.php(138): Piwik\\Tracker\\Visit->handle()\n#3 /opt/bitnami/matomo/core/Tracker/Handler.php(49): Piwik\\Tracker->trackRequest(Object(Piwik\\Tracker\\Request))\n#4 /opt/bitnami/matomo/core/Tracker.php(120): Piwik\\Tracker\\Handler->process(Object(Piwik\\Tracker), Object(Piwik\\Tracker\\RequestSet))\n#5 /opt/bitnami/matomo/core/Tracker.php(97): Pi in /opt/bitnami/matomo/core/Tracker/GoalManager.php on line 131, referer: https://mysite.com/
```

Thx for your help

**Comment by scysys** [comment]
Maybe you should try the update over your console again: `./path/to/matomo/console core:update`

**Comment by tsteur** [comment]
@Laul0 it seems like one file wasn't updated correctly maybe? Very likely the file `plugins/Goals/Tracker/GoalsRequestProcessor.php`. 

Could you try the manual three step update here? https://matomo.org/docs/update/#the-manual-three-step-update or try to update the content of that file only?

**Comment by Laul0** [comment]
I'll try to update from the console firstly because as I said, I'm using a Docker container (bitnami/matomo).

I'll keep you in touch

Thx for you help

**Comment by Laul0** [comment]
`core:update` doesn't change anythings:
<img width="555" alt="Screen Shot 2019-07-26 at 16 47 30" src="https://user-images.githubusercontent.com/15279205/61980558-1b1fd580-afc5-11e9-8a28-df0ab4849536.png">

**Comment by Laul0** [comment]
heyyy @tsteur, I performed the update manually and analytics works again ! 🤩

Thank you guys, you rock 👍🏻

**Comment by tsteur** [comment]
Glad it works now 👍
