### ISSUE TITLE
Can't login after update to v3.6.0-b3

### ISSUE THREAD

**Issue by Findus23** [matomo-org/matomo#13264]
I think this is a regression since #12208, so maybe @diosmosis knows more.

After updating Matomo, I got the following exception on login:

```
The following error just broke Matomo (v3.6.0-b3):

Too few arguments to function Piwik\Plugins\GoogleAuthenticator\SessionInitializer::initSession(), 1 passed in /var/www/matomo/plugins/Login/Controller.php on line 218 and exactly 2 expected

in

/var/www/matomo/plugins/GoogleAuthenticator/SessionInitializer.php line 31
``` 
I disabled `GoogleAuthenticator` and now after entering the correct password, the login page reappears. There is no error message or error in php and piwik log.

Any way I can help debug this?

-------
Bonus Bug: ( I am not sure if it is because of my setup, but it happened on two instances)

 After updating, I get redirected to `index.php?updateCorePlugins=1&module=CoreUpdater&action=`
which returns a 502, but again logs aren't that helpful.
```
2018/08/08 18:36:29 [error] 12368#12368: *82 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 127.0.0.1, server: dev.matomo, request: "GET /index.php?updateCorePlugins=1&module=CoreUpdater&action= HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.1-fpm.sock:", host: "dev.matomo", referrer: "https://dev.matomo/index.php?module=CoreUpdater&action="
```
Reloading the page, returns the normal login page.

**Comment by sgiehl** [comment]
I'll check the Google Authenticator now if it's still compatible

**Comment by Findus23** [comment]
@sgiehl I think this is a separate bug as I also can't login on my dev-instance without Google Authenticator. (Guess I should have updated it first)

**Comment by GreenReaper** [comment]
Perhaps this is #13260? Running into this myself now.

**Comment by Findus23** [comment]
Odd, I read through everything related to the pull request, but missed #13260. Thanks
